version: '3.3'
services:
  routine-database:
    container_name: routine-database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: 'routine'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - routine-db-data:/var/lib/postgresql/data

volumes:
  routine-db-data:
    driver: local
